// Format Handbook - the 12 registered content FORMATS.
//
// GENERATED FROM content_formats.md. Edit that file, then run:
//     dart run tool/sync_formats.dart
// Do not edit this file by hand. The markdown is the source of truth.
//
// A format is the HOW a piece of content is shaped. WHAT it is about lives in the
// idea library and never here. An idea can be executed as `problemFix` or as
// `doThisNotThat` on different days; both are the same idea.
//
// Why its own file rather than brand_system.dart: formats are the most volatile data
// in the app, because testing one five times is the loop this brand actually runs.
// brand_system.dart is imported by ten-plus modules, so a format change would
// otherwise rebuild all of them and couple the two.
//
// Why the handbook must never reference buckets or pillars: if a format's guidance
// says "for a humour bucket", then changing the bucket vocabulary requires touching
// every format. The axes stay separate by construction here.

// ============================================================================
// THE REGISTRY
// ============================================================================

/// One registered format. Every field maps to a field in `content_formats.md`.
class FormatSpec {
  /// Stable key. Ideas and posted performance reference this, so it is never
  /// renumbered — a renumber silently rewrites history.
  final String id;

  final String name;

  /// One sentence, what this shape is.
  final String definition;

  /// The beat order, written so a prompt can follow it literally. Never prose: the
  /// generator follows beats.
  final List<String> structure;

  /// When to reach for this format, in plain language.
  final String bestFor;

  /// Content types this suits, from [kContentTypeIds].
  final List<String> bestContentTypes;

  /// Goals this actually serves, from [kGoalIds]. This is what makes the
  /// recommendation in T-21 explainable rather than a guess.
  final List<String> bestGoals;

  /// The content type this format is the right answer for when several tie.
  ///
  /// Empty on most formats, and that is the intent. Without it, `problemFix`,
  /// `mistakesList`, `saveThisList` and `doThisNotThat` all scored 3 for
  /// imageSlideshowReel + nonFollowerReach, and the tie broke by declaration order —
  /// which recommended Mistakes List for an idea that is plainly a problem-to-fix.
  /// That is the worst failure mode this file can have: a wrong recommendation with
  /// no visible reason, which reads as a bug and erodes trust in every
  /// recommendation.
  final List<String> defaultFor;

  /// A real Fun Learning With Palak idea executed in this format.
  final String example;

  /// Checkable constraints. "Make it good" is not a rule; "no more than 9 words on
  /// screen" is.
  final List<String> generationRules;

  const FormatSpec({
    required this.id,
    required this.name,
    required this.definition,
    required this.structure,
    required this.bestFor,
    required this.bestContentTypes,
    required this.bestGoals,
    required this.example,
    required this.generationRules,
    this.defaultFor = const [],
  });

  /// Whether this format suits the given content type.
  bool supportsContentType(String contentType) => bestContentTypes.contains(contentType);

  /// Whether this format actually serves the given goal.
  bool servesGoal(String goal) => bestGoals.contains(goal);

  /// The scoring used when proposing a format for an idea.
  ///
  /// Deliberately simple and inspectable rather than clever. The reasoning is shown to
  /// the user in one line, so it has to be explainable in one line, and a heuristic
  /// nobody can audit is a heuristic nobody should trust. Content type is weighted
  /// above goal, because a format that cannot be produced in the chosen content type
  /// is not a weaker recommendation, it is an impossible one.
  int scoreFor({String? contentType, String? goal}) {
    var score = 0;
    if (contentType != null && supportsContentType(contentType)) score += 2;
    if (goal != null && servesGoal(goal)) score += 1;
    return score;
  }

  /// Whether this format declared itself the default for [contentType].
  bool isDefaultFor(String contentType) => defaultFor.contains(contentType);

  /// The one-line reasoning shown alongside a recommendation.
  String reason({String? contentType, String? goal}) {
    final parts = <String>[];
    if (contentType != null) {
      parts.add(supportsContentType(contentType)
          ? 'works as $contentType'
          : 'does not suit $contentType');
    }
    if (goal != null) {
      parts.add(servesGoal(goal) ? 'serves $goal' : 'weak for $goal');
    }
    return parts.isEmpty ? bestFor : parts.join(', ');
  }

  /// The block injected into a generation prompt for this format.
  ///
  /// Beats and rules, not the example. The example is one author's execution of the
  /// format and including it in every prompt invites the generator to re-tell it
  /// rather than follow the shape.
  String toPromptBlock() => '''
FORMAT: $name ($id)
Definition: $definition

Structure, in order:
${structure.map((b) => '  $b').join('\n')}

Generation rules:
${generationRules.map((r) => '  - $r').join('\n')}

Best for: $bestFor''';
}

class FormatLibrary {
  // -- 01 POV ----------------------------------------------------------
  static const FormatSpec pov = FormatSpec(
    id: 'pov',
    name: 'POV',
    definition:
        'First-person camera, as if the viewer is the parent living the moment.',
    structure: [
      'On-screen text declares the POV: `POV: you finally drank hot chai`',
      'The mess, or the small victory, immediately visible',
      'One beat of the child\'s point of view, usually Cuty or Rio',
      'The parent\'s quiet reaction',
      'One line of relatability text, no explanation',
    ],
    bestFor:
        'A feeling the viewer recognises in under two seconds. Works because the viewer supplies the story, so no exposition is needed.',
    bestContentTypes: ['reel', 'trialReel'],
    bestGoals: ['nonFollowerReach', 'relatability', 'shares', 'comments'],
    defaultFor: ['reel', 'trialReel'],
    example:
        '"POV: you finally drank hot chai while your child plays independently." Mumma sits down with a cup, Ria and Rio are absorbed transferring dal from bowl to bowl with two spoons. Cuty naps. No dialogue. On-screen text only at the top and the last frame.',
    generationRules: [
      'Camera is the viewer\'s eyes. Never show the parent\'s face from outside.',
      '`POV:` text appears in the first 6 words on screen and stays for at least 2 seconds.',
      'No voiceover narration in third person. Sound design and text only.',
      'Never explain the feeling. The viewer already has it.',
      'Max 3 text overlays for the whole piece.',
    ],
  );

  // -- 02 Do This, Not That --------------------------------------------
  static const FormatSpec doThisNotThat = FormatSpec(
    id: 'doThisNotThat',
    name: 'Do This, Not That',
    definition:
        'A correct behaviour paired with the wrong one it replaces.',
    structure: [
      'Frame A, the one that works, shown first',
      'Frame B, the familiar one that does not',
      'Why B fails, one clause only',
      'A or B restated as a rule the parent can remember',
    ],
    bestFor:
        'Replacing advice the parent is already ignoring. The pairing does the persuading, so the caption does not have to argue.',
    bestContentTypes: ['carousel', 'imageSlideshowReel', 'staticImage'],
    bestGoals: ['saves', 'shares', 'authority'],
    example:
        '"3 things to say instead of NO." Slide 1 `Say: "Aap ek kaam karo, phir main chai piyungi"` vs `Say: "NO"`. Slide 2 offering a turn instead of a refusal. Slide 3 narrating the child\'s version of being offered a turn.',
    generationRules: [
      'Always two columns or two panels. Never one.',
      'The correct option appears first in every pair. Order matters.',
      'Exactly 3 pairs per post. Not 2, not 5.',
      'Both options must be under 8 words on screen.',
      'No shame language toward the parent. The wrong option was reasonable.',
      'The closing line must be a rule, not a summary of the slides.',
    ],
  );

  // -- 03 Mistakes List ------------------------------------------------
  static const FormatSpec mistakesList = FormatSpec(
    id: 'mistakesList',
    name: 'Mistakes List',
    definition:
        'The errors the target parent is making, named honestly, then fixed.',
    structure: [
      'Call out the mistake the viewer is currently making',
      'Enumerate the mistakes, one per beat',
      'Each mistake gets its correction in the same beat',
      'Close on the one that matters most',
    ],
    bestFor:
        'Turning vague guilt into a specific checklist. The viewer recognises themselves, which is what earns the save.',
    bestContentTypes: ['carousel', 'imageSlideshowReel', 'reel'],
    bestGoals: ['saves', 'shares', 'nonFollowerReach'],
    example:
        '"Mistakes I made teaching Ria to be independent." Stopping her mid-task. Asking "what colour?" instead of "which one". Praising every attempt equally. Sitting her down to help.',
    generationRules: [
      '3 to 5 mistakes. Three is the default.',
      'Each mistake must be something a loving parent does by accident. Never stupidity.',
      'The correction is mandatory in the same beat. A list without fixes is guilt.',
      'First-person, as though the author made them. Not second-person accusation.',
      'No mistake may repeat a pillar\'s other lessons. Each stands alone.',
    ],
  );

  // -- 04 Problem → Fix ------------------------------------------------
  static const FormatSpec problemFix = FormatSpec(
    id: 'problemFix',
    name: 'Problem → Fix',
    definition:
        'One specific problem, the reason it persists, the jugaad fix, the result.',
    structure: [
      'The problem, shown not described',
      'The parent\'s first attempt, which fails',
      'The reason the usual approach fails, one line',
      'The fix, using something already in the house',
      'The result, the child participating',
      'A parent takeaway, one line',
    ],
    bestFor:
        'The flagship shape for this brand. It carries the whole problem-then-solution premise and it is the format the first six ideas in the library were written for.',
    bestContentTypes: ['reel', 'imageSlideshowReel', 'carousel'],
    bestGoals: ['nonFollowerReach', 'saves', 'relatability'],
    defaultFor: ['imageSlideshowReel'],
    example:
        '"Ria refuses to brush her teeth." Mumma counts to three. Ria clamps down. The count does not work on a 3-year-old. Mumma puts the brush in Ria\'s hand and turns it into a song she has to finish. Ria brushes. Takeaway: *"Give her the job, not the order."*',
    generationRules: [
      'The fix must cost nothing and use something already in the home. No buying.',
      'The first attempt must be a genuine attempt, not a strawman. It has to be one a parent would really try.',
      'The reason the usual approach fails is mandatory. Without it this becomes a lecture.',
      'The child ends the piece participating, not being managed.',
      'The takeaway is spoken to the parent, never to the child.',
      'Exactly 5 to 6 beats. Do not extend the middle.',
    ],
  );

  // -- 05 Exact Script -------------------------------------------------
  static const FormatSpec exactScript = FormatSpec(
    id: 'exactScript',
    name: 'Exact Script',
    definition:
        'The literal words to say, delivered so the parent can copy them.',
    structure: [
      'The situation, one line',
      'What most parents say, and why it lands badly',
      'The exact words to say instead, quoted verbatim',
      'The child\'s likely response',
      'One variation for a harder day',
    ],
    bestFor:
        'Language-building and TALK pillar content. Removes the cost of composing, so the parent acts today rather than later.',
    bestContentTypes: ['carousel', 'staticImage', 'imageSlideshowReel'],
    bestGoals: ['saves', 'shares', 'authority', 'follows'],
    example:
        '"What to say when Ria hits Rio." Instead of "don\'t hit", Mumma says *"Aap usko hurt kar rahe ho, rokao mujhe batana."* Rio responds by showing his hand. Variation for a repeat: name the rule, then the consequence, in two short sentences.',
    generationRules: [
      'The script must be quotable word for word. No paraphrasing in the on-screen text.',
      '8 to 12 words per quoted line. Longer is not memorised.',
      'Hinglish, the way the parent actually talks. Not formal English.',
      'Never shame the child in the quoted line.',
      'One variation only, not a list of alternatives.',
    ],
  );

  // -- 06 Expectation vs Reality ---------------------------------------
  static const FormatSpec expectationReality = FormatSpec(
    id: 'expectationReality',
    name: 'Expectation vs Reality',
    definition:
        'What the parent expects, set against what actually happens.',
    structure: [
      'The expectation, stated as the parent imagines it',
      'The expectation shown on screen',
      'The reality, unstyled and immediate',
      'The child doing the opposite',
      'The moment it becomes funny instead of frustrating',
    ],
    bestFor:
        'Humour that requires recognition to land. The gap is the joke, and the viewer closes it themselves.',
    bestContentTypes: ['reel', 'imageSlideshowReel', 'trialReel'],
    bestGoals: ['relatability', 'shares', 'nonFollowerReach', 'comments'],
    example:
        '"Expectation vs reality: teaching a 3-year-old to put on shoes." Expectation, a neat demonstration with Rio cooperating. Reality, Rio putting both shoes on, then a mitten on his foot, walking confidently. Mumma\'s face in the final beat.',
    generationRules: [
      'The reality beat must be genuinely unexpected, not a cute exaggeration.',
      'The child must be acting normally. Never a cartoon mishap.',
      'No punchline music or emoji overlays. The situation is the joke.',
      'The parent\'s reaction is the last beat and stays under 2 seconds.',
      'Never make the child\'s behaviour something to correct. It is the punchline, not a lesson.',
    ],
  );

  // -- 07 Personal Mistake ---------------------------------------------
  static const FormatSpec personalMistake = FormatSpec(
    id: 'personalMistake',
    name: 'Personal Mistake',
    definition:
        'Something the author did, owned without excuse, then repaired.',
    structure: [
      'What I did, plainly',
      'What I told myself about it',
      'What actually happened as a result',
      'What I do instead now',
      'What I would tell a friend in the same spot',
    ],
    bestFor:
        'Authority and relatability together. First-person accountability is the most trusted format on this platform and the least used.',
    bestContentTypes: ['reel', 'carousel', 'staticImage'],
    bestGoals: ['saves', 'shares', 'follows', 'relatability'],
    example:
        '"I let Ria watch TV to finish my work." Told myself it was ten minutes. It was forty, and by dinner she could not sit through dinner. Now the substitute is set up before the phone is, so the choice is never hers to make.',
    generationRules: [
      'First person throughout. Never "you".',
      'No excuse in beat 2. The self-justification is named so it can be discarded.',
      'No self-punishment, no performative confession. The tone is matter-of-fact.',
      'The repair must be specific and free. No product, no course, no book.',
      'Beat 5 addresses the viewer as an equal, never as a learner.',
    ],
  );

  // -- 08 Save This List -----------------------------------------------
  static const FormatSpec saveThisList = FormatSpec(
    id: 'saveThisList',
    name: 'Save This List',
    definition:
        'A reference set of items, designed to be saved and returned to.',
    structure: [
      'The promise, stated as what the list contains and who it is for',
      'Item 1, each one usable today with nothing bought',
      'Item 2',
      'Item 3',
      'Item 4',
      'Item 5',
      'Where to find them, i.e. a named drawer or shelf',
    ],
    bestFor:
        'Age-Based Skills and Try This At Home content. Saves are the only metric this format optimises for, so everything about it serves that.',
    bestContentTypes: ['carousel', 'staticImage'],
    bestGoals: ['saves', 'shares'],
    defaultFor: ['carousel', 'staticImage'],
    example:
        '"5 things in the kitchen drawer that keep a 3-year-old busy." Two spoons and a bowl for dal transfer. A plastic cup for water pouring. A muffin tin for sorting. A sieve for sifting. An empty container to fill and empty. The takeaway is the drawer, not the activities.',
    generationRules: [
      'Exactly 5 items. This is a hard number, not a target.',
      'Every item uses something already in the house. Zero purchases.',
      'One item per beat, one line of on-screen text each, max 9 words.',
      'The closing beat names a location, not a summary.',
      'No item may require adult supervision to be safe. This audience plays unsupervised.',
      'Never open with "save this post". The list has to earn the save.',
    ],
  );

  // -- 09 Numbered Framework -------------------------------------------
  static const FormatSpec numberedFramework = FormatSpec(
    id: 'numberedFramework',
    name: 'Numbered Framework',
    definition:
        'A teachable model in numbered steps, memorable as a sequence.',
    structure: [
      'Name the framework, so it can be referred to later by name',
      'Step 1, the entry point, the easiest',
      'Step 2',
      'Step 3',
      'Step 4',
      'The result, and when to move to the next step',
    ],
    bestFor:
        'TALK and DO content that needs to be recalled and repeated. A named framework is what parents describe to each other, which is distribution you do not pay for.',
    bestContentTypes: ['carousel', 'reel', 'imageSlideshowReel'],
    bestGoals: ['authority', 'saves', 'follows'],
    example:
        '"The 4-step brush routine that stopped the fight." Step 1 she chooses the song. Step 2 she holds the brush. Step 3 Mumma only taps the rhythm. Step 4 Ria finishes the last side. Move to step 3 only after two easy mornings.',
    generationRules: [
      '3 to 5 steps. Four is the default.',
      'Steps increase in difficulty. The first must be trivially easy.',
      'Each step is one instruction, max 10 words.',
      'The framework needs a name the parent can repeat. A generic list is not a framework.',
      'Include when to advance. A framework with no exit condition is a trap.',
    ],
  );

  // -- 10 Unpopular Opinion --------------------------------------------
  static const FormatSpec unpopularOpinion = FormatSpec(
    id: 'unpopularOpinion',
    name: 'Unpopular Opinion',
    definition:
        'A held position that contradicts common parenting advice, defended plainly.',
    structure: [
      'The opinion, stated in one line, no hedging',
      'The advice it contradicts, named fairly',
      'Why that advice is common',
      'The counter-case, argued not asserted',
      'The condition under which the common advice is right',
      'The honest close',
    ],
    bestFor:
        'Comments and profile visits. Disagreement is the cheapest engagement available, provided the position is argued rather than baited.',
    bestContentTypes: ['reel', 'trialReel', 'carousel'],
    bestGoals: ['comments', 'nonFollowerReach', 'follows'],
    example:
        '"Your child does not need praise." The common advice is to praise every attempt. It is common because it works on adults by analogy. For a 3-year-old, unearned praise teaches that the task was not interesting enough without an audience. Praise the effort once, then stay quiet. The common advice is right when the child is unsure whether they tried correctly.',
    generationRules: [
      'The opposing view must be stated at its strongest, not a straw version.',
      'Beat 5 is mandatory. An opinion with no boundary is a stunt.',
      'Never disagree for the sake of disagreement. If the position is mainstream, it is not this format.',
      'No contempt for parents who hold the other view. Argue the idea, not the person.',
      'The opinion must be defensible by the author in comments.',
    ],
  );

  // -- 11 Before You ---------------------------------------------------
  static const FormatSpec beforeYou = FormatSpec(
    id: 'beforeYou',
    name: 'Before You',
    definition:
        'Advice delivered as a pre-emptive warning about a specific moment.',
    structure: [
      'The moment named, so the parent recognises it before it happens',
      'What usually goes wrong there',
      'The mistake most parents make in that moment',
      'What to do instead, in time order',
      'What it looks like when it goes well',
    ],
    bestFor:
        'Preparing a parent for a predictable hard moment. The value is in the timing, so it has to be watchable *before* the moment arrives.',
    bestContentTypes: ['reel', 'imageSlideshowReel', 'carousel'],
    bestGoals: ['saves', 'nonFollowerReach', 'authority'],
    example:
        '"Before you let Ria choose her own clothes." The usual moment is a 20-minute stall over two options. The mistake is offering choices too early. Do it instead: lay out two complete outfits, let her choose between those, and keep the rejected one for tomorrow.',
    generationRules: [
      'The moment must be specific and recognisable in under 3 seconds.',
      'Advice must be actionable before the moment, not during it.',
      'The fix must be repeatable, not a one-off.',
      'No preview of the moment happening. The piece prepares, it does not tease.',
      'The closing beat must show the version that worked, not just the warning.',
    ],
  );

  // -- 12 Three Examples -----------------------------------------------
  static const FormatSpec threeExamples = FormatSpec(
    id: 'threeExamples',
    name: 'Three Examples',
    definition:
        'One idea demonstrated three different ways, so the parent picks the version that fits their child.',
    structure: [
      'The goal, one line, so the three are comparable',
      'Example 1, the easiest, the one that always works',
      'Example 2, the middle',
      'Example 3, the hardest, for a child who resists',
      'Which one to try first, given the child\'s temperament',
    ],
    bestFor:
        'Anyone whose advice has to survive contact with a real child. Three versions converts a rule into a choice, which is what makes it usable.',
    bestContentTypes: ['carousel', 'imageSlideshowReel', 'reel'],
    bestGoals: ['saves', 'shares', 'authority'],
    example:
        '"Three ways to end a tantrum." One, distract and leave. Two, stay close and stay silent. Three, name the feeling and wait. Start with one unless the child escalates to the floor.',
    generationRules: [
      'Exactly 3 examples, in ascending difficulty.',
      'All three must serve the same goal. Three different problems is not this format.',
      'Each example gets one beat and max 10 words on screen.',
      'The closing beat must tell the parent how to choose between them.',
      'None of the three may require anything bought or any professional.',
    ],
  );

  // -- 13 Quick Tip ----------------------------------------------------
  static const FormatSpec quickTip = FormatSpec(
    id: 'quickTip',
    name: 'Quick Tip',
    definition:
        'One simple activity or technique a parent can try immediately, demonstrated in a single beat.',
    structure: [
      'The situation, one line',
      'The quick technique, shown not described',
      'Why it works, one sentence',
      'The result, immediate',
    ],
    bestFor:
        'A single ₹0 activity or technique a parent can try today. This format owns **activity demonstrations**: water pouring, dal-chawal sensory play, tape pulling, spoon transfer, two-bowl sorting, and the rest of that family.',
    bestContentTypes: ['reel', 'trialReel', 'imageSlideshowReel'],
    bestGoals: ['nonFollowerReach', 'saves', 'shares'],
    example:
        '"Toddler maths — 1 biscuit = hungry, 2 = still hungry, 3 = MORE." Rio holds biscuits, expression escalates. Cuty unimpressed in background. No setup, just the reveal.',
    generationRules: [
      'Exactly one technique. Not a list.',
      'The technique uses something already in the house. Zero purchases.',
      '**Activity demonstrations belong here.** A setup → play → result beat sequence is not a failure to match another shape; it is this shape. The handbook previously had no format for "show the activity", so six real ideas — water pouring, dal chawal, tape pull, spoon transfer, pouring, simple sorting — matched nothing at all and were reported as unresolvable. Widening this format\'s stated scope is cheaper and more honest than inventing an Activity Demonstration format to absorb them.',
      'No explanation of why the child behaves this way. The technique speaks.',
      'On-screen text max 8 words. The visual is the hook.',
      'Duration 10-15 seconds if Reel/Trial Reel.',
    ],
  );

  // -- 14 Mini Story ---------------------------------------------------
  static const FormatSpec miniStory = FormatSpec(
    id: 'miniStory',
    name: 'Mini Story',
    definition:
        'A short narrative with a clear beginning, middle and end, told through Ria/Rio/Cuty.',
    structure: [
      'The setup — character wants something',
      'The obstacle — it doesn\'t go smoothly',
      'The turning point — a small intervention or discovery',
      'The resolution — character succeeds or learns',
      'The parent takeaway, one line',
    ],
    bestFor:
        'Emotional connection through character moments. The viewer watches for Ria/Rio/Cuty, not just the activity.',
    bestContentTypes: ['imageSlideshowReel', 'reel', 'carousel'],
    bestGoals: ['relatability', 'shares', 'follows'],
    example:
        '"Cuty is stuck under the sofa." Ria panics. Rio thinks. Mumma suggests the broom handle. Cuty rescued. Takeaway: "Sometimes the solution is already in your hand."',
    generationRules: [
      'Exactly 5 beats. Not 3, not 7.',
      'Ria, Rio or Cuty must be the protagonist. Never a generic child.',
      'The obstacle must be solvable with a household object, not magic.',
      'The takeaway addresses the parent, not the child.',
      'No moralising. The story teaches; the takeaway names the lesson.',
    ],
  );

  // -- 15 This or That -------------------------------------------------
  static const FormatSpec thisOrThat = FormatSpec(
    id: 'thisOrThat',
    name: 'This or That',
    definition:
        'A direct choice between two options, presented so the audience picks one.',
    structure: [
      'The question, visual and immediate',
      'Option A, shown',
      'Option B, shown',
      'The parent context — why this choice matters',
      'A gentle nudge toward the better option, without shame',
    ],
    bestFor:
        'Engagement and comments. The format is literally a question the viewer answers.',
    bestContentTypes: ['carousel', 'staticImage', 'story'],
    bestGoals: ['comments', 'relatability', 'shares'],
    example:
        '"Toddler wants phone at dinner. Phone OR spoon-transfer activity?" Show both. Spoon-transfer wins. Caption: "Which one buys you 15 minutes of hot chai?"',
    generationRules: [
      'Always two options. Never three.',
      'Both options visually distinct. Not "red spoon" vs "blue spoon".',
      'The better option is not morally superior. It is practically superior.',
      'The nudge is optional. The audience\'s vote is the point.',
      'Max 6 words per option on screen.',
    ],
  );

  // -- 16 Question → Answer --------------------------------------------
  static const FormatSpec questionAnswer = FormatSpec(
    id: 'questionAnswer',
    name: 'Question → Answer',
    definition:
        'One parent question, the exact words to say, and why those words work.',
    structure: [
      'The exact question a parent asks',
      'The common answer that lands badly',
      'The exact words to say instead, quoted verbatim',
      'Why this phrasing works, one sentence',
      'One variation for a harder moment',
    ],
    bestFor:
        'Language-building and TALK pillar content. Removes the cost of composing, so the parent acts today rather than later.',
    bestContentTypes: ['carousel', 'staticImage', 'imageSlideshowReel'],
    bestGoals: ['saves', 'shares', 'authority', 'follows'],
    example:
        '"What to say when toddler asks for phone at lunch." Common: "No phone." Instead: "Phone baad mein. Abhi chhuri-chammach se khelo." Variation for escalation: "Phone baad mein. Pehle ek kaam karo, phir phone."',
    generationRules: [
      'The quoted line must be quotable word for word. No paraphrasing.',
      '8 to 12 words per quoted line. Longer is not memorised.',
      'Hinglish, the way the parent actually talks. Not formal English.',
      'Never shame the child in the quoted line.',
      'One variation only, not a list of alternatives.',
      'The "why it works" sentence is mandatory — otherwise it is a script, not a lesson.',
    ],
  );

  static const List<FormatSpec> all = [
    pov,
    doThisNotThat,
    mistakesList,
    problemFix,
    exactScript,
    expectationReality,
    personalMistake,
    saveThisList,
    numberedFramework,
    unpopularOpinion,
    beforeYou,
    threeExamples,
    quickTip,
    miniStory,
    thisOrThat,
    questionAnswer,
  ];

  static FormatSpec? byId(String id) {
    for (final f in all) {
      if (f.id == id) return f;
    }
    return null;
  }

  static FormatSpec? byName(String name) {
    final lower = name.trim().toLowerCase();
    for (final f in all) {
      if (f.name.toLowerCase() == lower) return f;
    }
    return null;
  }

  /// Formats that suit a given content type.
  static List<FormatSpec> forContentType(String contentType) =>
      all.where((f) => f.supportsContentType(contentType)).toList();

  /// Formats that serve a given goal.
  static List<FormatSpec> forGoal(String goal) =>
      all.where((f) => f.servesGoal(goal)).toList();

  /// Proposes a format, with reasoning.
  ///
  /// Returns null when nothing matches, and the caller must surface that as a
  /// missing format rather than substituting a default. Silently falling back to
  /// [problemFix] is how an unsupported format becomes a Problem Fix with no trace,
  /// which makes the five-test loop unreadable: you would be comparing results across
  /// different shapes and blaming the format.
  static FormatSpec? recommend({String? contentType, String? goal}) {
    FormatSpec? best;
    var bestScore = 0;
    var bestIsDefault = false;
    for (final f in all) {
      final s = f.scoreFor(contentType: contentType, goal: goal);
      final isDefault =
          contentType != null && f.isDefaultFor(contentType);
      // A declared default only wins a tie, never a real score difference. Scored
      // this way on purpose: a default that outranked a better match would make
      // `Default for` a shortcut, and the whole point of declaring it was to break
      // ties honestly.
      final better = s > bestScore || (s == bestScore && isDefault && !bestIsDefault);
      if (better && s > 0) {
        bestScore = s;
        bestIsDefault = isDefault;
        best = f;
      }
    }
    return bestScore == 0 ? null : best;
  }
}

// ============================================================================
// THE TWO AXES A FORMAT REFERENCES
// ============================================================================
//
// These are declared here rather than imported from brand_system.dart, because the
// handbook must not depend on the modules it is meant to keep independent. When the
// ContentType enum is migrated into this file (task T-14), these lists become that
// enum's ids and this section collapses into it.
//
// Until then they are strings, and `FormatLibrary.recommend` will happily score
// against an id that does not exist. `validateAxes` exists to catch that.

/// The six content types, in the ids the handbook uses.
const List<String> kContentTypeIds = [
  'reel',
  'trialReel',
  'carousel',
  'staticImage',
  'imageSlideshowReel',
  'story',
];

/// The goals, in the ids the handbook uses.
const List<String> kGoalIds = [
  'reach',
  'nonFollowerReach',
  'saves',
  'shares',
  'comments',
  'relatability',
  'authority',
  'follows',
];

/// Content types the handbook references that the app cannot yet produce.
///
/// [imageSlideshowReel] and [story] are the two, and both are missing from the
/// ContentFormat enum. This is deliberately a visible list rather than a silent
/// filter: a format recommending a content type that cannot be generated is the kind
/// of thing that looks fine in the UI and fails at the last step.
const List<String> kUnimplementedContentTypes = [
  'imageSlideshowReel',
  'story',
];

/// Reports handbook references that do not resolve to a known id.
///
/// Returns a human-readable problem per line, empty when the handbook is consistent.
List<String> validateAxes() {
  final problems = <String>[];
  for (final f in FormatLibrary.all) {
    for (final t in f.bestContentTypes) {
      if (!kContentTypeIds.contains(t)) {
        problems.add('${f.id}: unknown content type "$t"');
      }
    }
    for (final g in f.bestGoals) {
      if (!kGoalIds.contains(g)) {
        problems.add('${f.id}: unknown goal "$g"');
      }
    }
  }
  return problems;
}