import 'dart:io';

import 'classify_ideas.dart';
import 'migration_state.dart';

/// Emits a markdown review sheet for one axis, in the form meant to be approved in
/// bulk.
///
///   dart run tool/review_sheet.dart pillar
///   dart run tool/review_sheet.dart series
///   dart run tool/review_sheet.dart all
///
/// One row per idea, with the proposed value, its confidence, and the reason. The
/// `Decision` column is left blank on purpose: the sheet is for a human to fill, and
/// a tool that pre-fills it has already made the decision it was built to ask about.
///
/// ── Why markdown and not CSV ─────────────────────────────────────────────────
///
/// The decisions files are CSV because code reads them. This is markdown because a
/// person reads them, and a 45-row table is reviewed in one pass whereas 45 CSV lines
/// are not.

const _axes = ['pillar', 'series', 'contentType', 'productionMethod', 'goal'];

void main(List<String> argv) {
  final wanted = argv.isEmpty || argv.first == 'all'
      ? _axes
      : _axes.where((a) => argv.contains(a)).toList();

  if (wanted.isEmpty) {
    stderr.writeln('Unknown axis. One of: ${_axes.join(', ')}, or all');
    exitCode = 1;
    return;
  }

  final file = File('content_ideas.md');
  if (!file.existsSync()) {
    stderr.writeln('content_ideas.md not found. Run from the project root.');
    exitCode = 1;
    return;
  }
  final ideas = parseFile(file.readAsStringSync()).ideas;

  final decided = <String, Map<String, Decision>>{
    'pillar': readDecisions('tool/pillar_decisions.csv', requireEvidence: true),
    'series': const {},
    'contentType': const {},
    'productionMethod': const {},
    'goal': const {},
  };

  final out = StringBuffer();
  out.writeln('# Idea review sheet');
  out.writeln();
  out.writeln('Generated by `tool/review_sheet.dart`. Read-only: nothing is written '
      'to `content_ideas.md`.');
  out.writeln();
  out.writeln('Fill the **Decision** column with `approve` or the corrected value, '
      'then move');
  out.writeln('the row into the matching decisions CSV. An idea that already has a '
      'human');
  out.writeln('decision is shown as settled and needs nothing.');
  out.writeln();

  for (final axis in wanted) {
    final rows = <List<String>>[];

    for (final idea in ideas) {
      final existing = decided[axis]?[idea.id];
      if (existing != null) {
        final held = existing.state != MigrationState.approved;
        rows.add([
          idea.id,
          idea.heading,
          existing.value.isEmpty ? '(none)' : existing.value,
          existing.state.name,
          existing.note,
          held ? 'pending' : 'settled',
        ]);
        continue;
      }

      final c = Classifier(idea);
      late final Proposal p;
      switch (axis) {
        case 'pillar':
          p = c.classifyPillar();
        case 'series':
          p = c.classifySeries();
        case 'contentType':
          p = c.classifyContentType();
        case 'productionMethod':
          p = c.classifyProduction();
        default:
          p = c.classifyGoal();
      }

      if (p.value.isEmpty) continue;
      rows.add([
        idea.id,
        idea.heading,
        p.value,
        p.confidence.name,
        p.reason,
        '',
      ]);
    }

    if (rows.isEmpty) {
      out.writeln('## $axis');
      out.writeln();
      out.writeln('Nothing open.');
      out.writeln();
      continue;
    }

    final high = rows.where((r) => r[3] == 'high').length;
    final medium = rows.where((r) => r[3] == 'medium').length;
    final low = rows.where((r) => r[3] == 'low').length;

    out.writeln('## $axis');
    out.writeln();
    out.writeln('$high high · $medium medium · $low low');
    out.writeln();
    out.writeln('| Idea | Title | Proposed | Confidence | Reason | Decision |');
    out.writeln('| --- | --- | --- | --- | --- | --- |');
    for (final r in rows) {
      out.writeln('| `${r[0]}` | ${r[1]} | **${r[2]}** | ${r[3]} | ${r[4]} | ${r[5]} |');
    }
    out.writeln();
  }

  final path = 'tool/review_sheet.md';
  File(path).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $path');
  for (final axis in wanted) {
    stdout.writeln('  $axis');
  }
}